export const Users = [
  {
    id: 1,
    firstName: 'Peter',
    lastName: 'Tunde',
    email: 'petertunde@gmail.com',
    password: 'password',
    type: 'client',
    isAdmin: false,
  },
  {
    id: 2,
    firstName: 'Aisha',
    lastName: 'Lawal',
    email: 'aishalawal23@gmail.com',
    password: 'password',
    type: 'client',
    isAdmin: false,
  },
  {
    id: 3,
    firstName: 'Chukwudi',
    lastName: 'James',
    email: 'chukwudi.james@gmail.com',
    password: 'password',
    type: 'client',
    isAdmin: false,
  },
  {
    id: 4,
    firstName: 'Bill',
    lastName: 'Mark',
    email: 'billmark56@gmail.com',
    password: 'password',
    type: 'client',
    isAdmin: false,
  },
  {
    id: 5,
    firstName: 'Amaka',
    lastName: 'Padi',
    email: 'amaka.padi@gmail.com',
    password: 'password',
    type: 'staff',
    isAdmin: false,
  },
  {
    id: 1,
    firstName: 'Jeffery',
    lastName: 'Sunday',
    email: 'jefferysunday12@gmail.com',
    password: 'password',
    type: 'staff',
    isAdmin: false,
  },
  {
    id: 1,
    firstName: 'Onu',
    lastName: 'Monday',
    email: 'onumonday@gmail.com',
    password: 'password',
    type: 'staff',
    isAdmin: true,
  },
];

export const Transaction = [];
