export const Users = [
  {
    id: 1,
    firstName: 'Peter',
    lastName: 'Tunde',
    email: 'petertunde@gmail.com',
    password: 'password',
    type: 'client',
    isAdmin: false,
  },
  {
    id: 2,
    firstName: 'Aisha',
    lastName: 'Lawal',
    email: 'aishalawal23@gmail.com',
    password: 'password',
    type: 'client',
    isAdmin: false,
  },
  {
    id: 3,
    firstName: 'Chukwudi',
    lastName: 'James',
    email: 'chukwudi.james@gmail.com',
    password: 'password',
    type: 'client',
    isAdmin: false,
  },
  {
    id: 4,
    firstName: 'Bill',
    lastName: 'Mark',
    email: 'billmark56@gmail.com',
    password: 'password',
    type: 'client',
    isAdmin: false,
  },
  {
    id: 5,
    firstName: 'Amaka',
    lastName: 'Padi',
    email: 'amaka.padi@gmail.com',
    password: 'password',
    type: 'staff',
    isAdmin: false,
  },
  {
    id: 6,
    firstName: 'Jeffery',
    lastName: 'Sunday',
    email: 'jefferysunday12@gmail.com',
    password: 'password',
    type: 'staff',
    isAdmin: false,
  },
  {
    id: 1,
    firstName: 'Onu',
    lastName: 'Monday',
    email: 'onumonday@gmail.com',
    password: 'password',
    type: 'staff',
    isAdmin: true,
  },
];

export const Transaction = [];

export const Accounts = [
  {
    _id: 1,
    accountNumber: 1004837498,
    createdOn: new Date().getTime,
    owner: 1,
    type: 'savings',
    status: 'active',
    balance: 0.00,
  },
  {
    _id: 2,
    accountNumber: 1004837498,
    createdOn: new Date().getTime,
    owner: 1,
    type: 'current',
    status: 'active',
    balance: 0.00,
  },
  {
    _id: 1,
    accountNumber: 1004839098,
    createdOn: new Date().getTime,
    owner: 2,
    type: 'savings',
    status: 'active',
    balance: 0.00,
  },
  {
    _id: 1,
    accountNumber: 1003437498,
    createdOn: new Date().getTime,
    owner: 3,
    type: 'savings',
    status: 'dormant',
    balance: 0.00,
  },
  {
    _id: 1,
    accountNumber: 1004837498,
    createdOn: new Date().getTime,
    owner: 4,
    type: 'savings',
    status: 'active',
    balance: 0.00,
  },
];
