export const Users = [
  {
    firstName: 'Peter',
    lastName: 'Tunde',
    email: 'petertunde@gmail.com',
    password: 'password',
    type: 'client',
    isAdmin: false,
  },
  {
    firstName: 'Aisha',
    lastName: 'Lawal',
    email: 'aishalawal23@gmail.com',
    password: 'password',
    type: 'client',
    isAdmin: false,
  },
  {
    firstName: 'Chukwudi',
    lastName: 'James',
    email: 'chukwudi.james@gmail.com',
    password: 'password',
    type: 'client',
    isAdmin: false,
  },
  {
    firstName: 'Bill',
    lastName: 'Mark',
    email: 'billmark56@gmail.com',
    password: 'password',
    type: 'client',
    isAdmin: false,
  },
  {
    firstName: 'Amaka',
    lastName: 'Padi',
    email: 'amaka.padi@gmail.com',
    password: 'password',
    type: 'staff',
    isAdmin: false,
  },
  {
    firstName: 'Jeffery',
    lastName: 'Sunday',
    email: 'jefferysunday12@gmail.com',
    password: 'password',
    type: 'staff',
    isAdmin: false,
  },
  {
    firstName: 'Onu',
    lastName: 'Monday',
    email: 'onumonday@gmail.com',
    password: 'password',
    type: 'staff',
    isAdmin: true,
  },
];

export const Accounts = [
  {
    accountNumber: 1004875498,
    createdOn: new Date().getTime,
    owner: 1,
    type: 'savings',
    status: 'active',
    balance: 340000.00,
  },
  {
    accountNumber: 1004870909,
    createdOn: new Date().getTime,
    owner: 1,
    type: 'savings',
    status: 'active',
    balance: 3000.00,
  },
  {
    accountNumber: 1004848398,
    createdOn: new Date().getTime,
    owner: 1,
    type: 'savings',
    status: 'active',
    balance: 0.00,
  },
  {
    accountNumber: 1003847890,
    createdOn: new Date().getTime,
    owner: 1,
    type: 'savings',
    status: 'active',
    balance: 100.00,
  },
  {
    accountNumber: 1000047890,
    createdOn: new Date().getTime,
    owner: 1,
    type: 'savings',
    status: 'active',
    balance: 400000.00,
  },
  {
    accountNumber: 1004839098,
    createdOn: new Date().getTime,
    owner: 2,
    type: 'savings',
    status: 'dormant',
    balance: 0.00,
  },
  {
    accountNumber: 1003437498,
    createdOn: new Date().getTime,
    owner: 3,
    type: 'savings',
    status: 'dormant',
    balance: 0.00,
  },
  {
    accountNumber: 1004837498,
    createdOn: new Date().getTime,
    owner: 4,
    type: 'savings',
    status: 'dormant',
    balance: 0.00,
  },
  {
    accountNumber: 1004809890,
    createdOn: new Date().getTime,
    owner: 4,
    type: 'savings',
    status: 'dormant',
    balance: 0.00,
  },
  {
    accountNumber: 1007877890,
    createdOn: new Date().getTime,
    owner: 4,
    type: 'savings',
    status: 'active',
    balance: 0.00,
  },
];

export const Transactions = [
  {
    createdOn: new Date().getDate,
    type: 'credit',
    accountNumber: 1004837498,
    cashier: 5,
    amount: 150000.00,
    oldBalance: 0.00,
    newBalance: 150000.00,
  },
  {
    createdOn: new Date().getDate,
    type: 'credit',
    accountNumber: 1004837498,
    cashier: 5,
    amount: 150000.00,
    oldBalance: 0.00,
    newBalance: 150000.00,
  },
  {
    createdOn: new Date().getDate,
    type: 'credit',
    accountNumber: 1004837498,
    cashier: 5,
    amount: 10000.00,
    oldBalance: 150000.00,
    newBalance: 160000.00,
  },
  {
    createdOn: new Date().getDate,
    type: 'credit',
    accountNumber: 1004837498,
    cashier: 5,
    amount: 35000.00,
    oldBalance: 160000.00,
    newBalance: 125000.00,
  },
];
